#!/bin/sh

SYSTEM=$(uname)

if [ -d $SYSTEM ]; then
    CFG_FOLDERS=`ls $SYSTEM`
    echo "Installing dotfiles for $SYSTEM system"
    for FOLDER in $CFG_FOLDERS
    do
        echo "[+] $FOLDER"
        stow --restow $FOLDER -d $SYSTEM -t $HOME
    done
else
    echo "It seems that is no configuration for your $HOSTNAME system."
fi
