#!/bin/sh

DARWIN_FILES="nvim tmux zsh alacritty"
LINUX_FILES="nvim tmux zsh alacritty i3 xinitrc rofi"

SYSTEM=$(uname)
FILES_FOLDER="files"

if [ -d $FILES_FOLDER ]; then

    echo "Installing dotfiles for $SYSTEM system"
    if [ $SYSTEM == "Darwin" ]; then
	CFG_FOLDERS=$DARWIN_FILES
    elif [ $SYSTEM == "Linux" ]; then
    	CFG_FOLDERS=$LINUX_FILES
    fi

    for FOLDER in $CFG_FOLDERS; do
        echo "[+] $FOLDER"
        echo stow $FOLDER -d $FILES_FOLDER -t $HOME
        stow --restow $FOLDER -d $FILES_FOLDER -t $HOME
    done

else
    echo "Files folder not found... Like, what the fuck?"
fi
