#! /bin/sh

bspc monitor -d term web code music another 

bspc config border_width                0
bspc config window_gap                  15
bspc config focus_follows_pointer       true
bspc config remove_unplugged_monitors   true

#bspc config split_ratio                 0.
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/Images/Wallpapers/default.png
polybar top &
